version: 0.2


phases:
  install:
    commands:
      - npm install
    finally:
      - echo Moving to pre-build stage
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo Moving to build stage
  build:
    commands:
      - echo Entered the build phase...
      - npm run build

    finally:
      - echo Moving to post build
  post_build:
    commands:
      - echo Entered the post_build phase....

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - scripts/**
  name: wecare_data
